export const STATES=Object.freeze(["DRAFT","ACTIVE","SUSPENDED","COMPLETED","CANCELLED"]);
export class AuthorizationError extends Error{constructor(m="Access denied"){super(m);this.name="AuthorizationError"}}
export class ValidationError extends Error{constructor(m){super(m);this.name="ValidationError"}}
const next={DRAFT:["ACTIVE","CANCELLED"],ACTIVE:["SUSPENDED","COMPLETED","CANCELLED"],SUSPENDED:["ACTIVE","CANCELLED"],COMPLETED:[],CANCELLED:[]};
const auth=(c,p)=>{if(!c?.tenantId||!c?.principalId||!c.permissions?.includes(p))throw new AuthorizationError()};
export class RecordRepository{#records=new Map();create(c,d){auth(c,"record:create");if(!d?.reference||!d?.category)throw new ValidationError("Reference and category required");const r={id:crypto.randomUUID(),tenantId:c.tenantId,reference:d.reference,category:d.category,state:"DRAFT",version:1,history:[{state:"DRAFT",actor:c.principalId,at:new Date().toISOString()}]};this.#records.set(r.id,r);return structuredClone(r)}transition(c,id,state,reason){auth(c,"record:transition");const r=this.#records.get(id);if(!r||r.tenantId!==c.tenantId)throw new AuthorizationError();if(!next[r.state].includes(state)||!reason?.trim())throw new ValidationError("Invalid transition or reason");r.state=state;r.version++;r.history.push({state,reason,actor:c.principalId,at:new Date().toISOString()});return structuredClone(r)}list(c){auth(c,"record:read");return [...this.#records.values()].filter(r=>r.tenantId===c.tenantId).map(structuredClone)}}
export function validateMaterialChange(r,{approvalConfirmed,preconditionsMet}={}){if(!r||!approvalConfirmed||!preconditionsMet)throw new ValidationError("Material change conditions not met");return true}
export function audit(event,actor,resourceId){if(!event||!actor||!resourceId)throw new ValidationError("Incomplete audit event");return Object.freeze({event,actor,resourceId,at:new Date().toISOString()})}
export function controlledException(code,message,context={}){if(!code||!message)throw new ValidationError("Exception code and message required");return Object.freeze({code,message,context:structuredClone(context),status:"OPEN",at:new Date().toISOString()})}
export function report(c,repo){auth(c,"report:read");return repo.list(c).reduce((x,r)=>(x.total++,x.byState[r.state]=(x.byState[r.state]??0)+1,x),{total:0,byState:{}})}
