export const STATES=Object.freeze({DRAFT:"DRAFT",ACTIVE:"ACTIVE",SUSPENDED:"SUSPENDED",COMPLETED:"COMPLETED",CANCELLED:"CANCELLED"});
export class AuthorizationError extends Error{constructor(message="Forbidden"){super(message);this.name="AuthorizationError";}}
export class ValidationError extends Error{constructor(message){super(message);this.name="ValidationError";}}
const transitions={DRAFT:new Set(["ACTIVE","CANCELLED"]),ACTIVE:new Set(["SUSPENDED","COMPLETED","CANCELLED"]),SUSPENDED:new Set(["ACTIVE","CANCELLED"]),COMPLETED:new Set(),CANCELLED:new Set()};
export class RecordRepository{constructor(){this.records=new Map();this.auditLog=[];}#auth(c,p,t){if(!c?.principalId||c.tenantId!==t||!c.permissions?.includes(p))throw new AuthorizationError();}
create(c,{id,tenantId,reference,category}){this.#auth(c,"record:create",tenantId);if(!id||!reference||!category)throw new ValidationError("reference and category are required");if(this.records.has(id))throw new ValidationError("record already exists");const r={id,tenantId,reference,category,state:STATES.DRAFT,history:[{from:null,to:STATES.DRAFT,actor:c.principalId}]};this.records.set(id,r);this.audit("RECORD_CREATED",c,id);return structuredClone(r);}
get(c,id){const r=this.records.get(id);if(!r||r.tenantId!==c?.tenantId)throw new AuthorizationError();this.#auth(c,"record:read",r.tenantId);return structuredClone(r);}
transition(c,id,to,reason){const r=this.records.get(id);if(!r||r.tenantId!==c?.tenantId)throw new AuthorizationError();this.#auth(c,"record:transition",r.tenantId);if(!transitions[r.state]?.has(to))throw new ValidationError("invalid lifecycle transition");if(!reason)throw new ValidationError("transition reason is required");const from=r.state;r.state=to;r.history.push({from,to,reason,actor:c.principalId});this.audit("STATE_CHANGED",c,id,{from,to,reason});return structuredClone(r);}
validateMaterialChange(i){if(!i?.approvalConfirmed||!i?.preconditionsMet)throw new ValidationError("approval and mandatory preconditions are required");return true;}
audit(event,c,resourceId,details={}){this.auditLog.push({event,principalId:c?.principalId,tenantId:c?.tenantId,resourceId,details});}
controlledException(code,message,c,id){if(!code||!message)throw new ValidationError("exception code and message are required");this.audit("CONTROLLED_EXCEPTION",c,id,{code,message});return{code,message,status:"OPEN"};}
report(c){this.#auth(c,"report:read",c.tenantId);return[...this.records.values()].filter(r=>r.tenantId===c.tenantId).reduce((a,r)=>(a[r.state]=(a[r.state]||0)+1,a),{});}}