import test from "node:test";
import assert from "node:assert/strict";
import { requirementBindings } from "../dist/packages/requirements/registry.js";
import { AuthoritativeRecordService, AuthorizationService, BusinessValidationService, AuditEvidenceService, ExceptionHandlingService, GovernedReportingService } from "../dist/packages/capabilities/services.js";
const req=id=>{const r=requirementBindings.find(x=>x.id===id);assert.ok(r,"Missing governed requirement: "+id);return r};
const ctx=id=>({tenantId:"wave-07-ch469",principalId:"wave-07-runner",correlationId:id});

test("REQ-46901 / SRS-FR-2359: authoritative lifecycle",async()=>{const r=req("REQ-46901");assert.equal(r.pattern,"XX01");const s=new AuthoritativeRecordService();await s.execute(r,{context:ctx("46901-create"),payload:{operation:"create",record:{id:"46901-record",tenantId:"wave-07-ch469",version:1,state:"OPEN",data:{source:"wave-07"}}}});const u=await s.execute(r,{context:ctx("46901-update"),payload:{operation:"update",tenantId:"wave-07-ch469",id:"46901-record",expectedVersion:1,patch:{state:"CLOSED"}}});assert.equal(u.data.payload.record.version,2);assert.equal(u.data.payload.record.state,"CLOSED");assert.throws(()=>s.execute(r,{context:ctx("46901-stale"),payload:{operation:"update",tenantId:"wave-07-ch469",id:"46901-record",expectedVersion:1,patch:{state:"REOPENED"}}}),/RECORD_VERSION_CONFLICT/)});
test("REQ-46902 / SRS-FR-2360: authorization",async()=>{const r=req("REQ-46902");assert.equal(r.pattern,"XX02");const s=new AuthorizationService();const d=await s.execute(r,{context:ctx("46902-deny"),payload:{operation:"decide",request:{tenantId:"wave-07-ch469",principalId:"actor-46902",action:"material.update",resource:"authoritative-record"},policies:[{tenantId:"wave-07-ch469",principalId:"actor-46902",actions:["material.update"],resources:["authoritative-record"],effect:"ALLOW"},{tenantId:"wave-07-ch469",principalId:"actor-46902",actions:["material.update"],resources:["authoritative-record"],effect:"DENY"}]}});assert.equal(d.data.payload.decision.effect,"DENY");const dd=await s.execute(r,{context:ctx("46902-default"),payload:{operation:"decide",request:{tenantId:"wave-07-ch469",principalId:"unlisted",action:"material.delete",resource:"authoritative-record"}}});assert.equal(dd.data.payload.decision.effect,"DENY")});
test("REQ-46903 / SRS-FR-2361: business validation",async()=>{const r=req("REQ-46903");assert.equal(r.pattern,"XX03");const s=new BusinessValidationService();s.addRule({id:"46903-positive-amount",evaluate:i=>i?.amount>0?null:{code:"MANDATORY_CONDITION_FAILED",message:"Amount must be positive",severity:"ERROR"}});const v=await s.execute(r,{context:ctx("46903-valid"),payload:{operation:"validate",input:{amount:100}}});assert.equal(v.data.payload.validation.valid,true);const i=await s.execute(r,{context:ctx("46903-invalid"),payload:{operation:"validate",input:{amount:0}}});assert.equal(i.data.payload.validation.valid,false)});
test("REQ-46904 / SRS-FR-2362: audit integrity",async()=>{const r=req("REQ-46904");assert.equal(r.pattern,"XX04");const s=new AuditEvidenceService();const a=await s.execute(r,{context:ctx("46904-append"),payload:{operation:"append",evidence:{id:"46904-evidence",tenantId:"wave-07-ch469",requirementId:"REQ-46904",action:"MATERIAL_EVENT",principalId:"wave-07-runner",correlationId:"46904-append",occurredAt:"2026-09-25T03:00:00.000Z",payload:{result:"PASS"}}}});assert.match(a.data.payload.evidence.integrityHash,/^[a-f0-9]{64}$/);const own=await s.execute(r,{context:ctx("46904-list"),payload:{operation:"listByRequirement",tenantId:"wave-07-ch469",requirementId:"REQ-46904"}});assert.equal(own.data.payload.evidence.length,1)});
test("REQ-46905 / SRS-FR-2363: exception lifecycle",async()=>{const r=req("REQ-46905");assert.equal(r.pattern,"XX05");const s=new ExceptionHandlingService();await s.execute(r,{context:ctx("46905-create"),payload:{operation:"create",exception:{id:"46905-exception",tenantId:"wave-07-ch469",requirementId:"REQ-46905",code:"CONTROLLED_FAILURE",message:"Acceptance scenario",idempotencyKey:"46905-idempotency",createdAt:"2026-09-25T03:00:00.000Z"}}});const retry=await s.execute(r,{context:ctx("46905-retry"),payload:{operation:"transition",tenantId:"wave-07-ch469",id:"46905-exception",patch:{state:"RETRYING"}}});assert.equal(retry.data.payload.exception.state,"RETRYING");const resolved=await s.execute(r,{context:ctx("46905-resolve"),payload:{operation:"transition",tenantId:"wave-07-ch469",id:"46905-exception",patch:{state:"RESOLVED"}}});assert.equal(resolved.data.payload.exception.state,"RESOLVED");assert.throws(()=>s.execute(r,{context:ctx("46905-invalid"),payload:{operation:"transition",tenantId:"wave-07-ch469",id:"46905-exception",patch:{state:"RETRYING"}}}),/EXCEPTION_INVALID_TRANSITION/)});
test("REQ-46906 / SRS-FR-2364: governed reporting",async()=>{const r=req("REQ-46906");assert.equal(r.pattern,"XX06");const s=new GovernedReportingService();await s.execute(r,{context:ctx("46906-publish"),payload:{operation:"publish",row:{tenantId:"wave-07-ch469",reportId:"status-performance",values:{state:"OPEN",performance:99},sourceRequirementIds:["REQ-46906"],generatedAt:"2026-09-25T03:00:00.000Z"}}});const own=await s.execute(r,{context:ctx("46906-query"),payload:{operation:"query",request:{tenantId:"wave-07-ch469",reportId:"status-performance",filters:{state:"OPEN"},limit:10}}});assert.equal(own.data.payload.rows.length,1);const other=await s.execute(r,{context:{...ctx("46906-other"),tenantId:"other-tenant"},payload:{operation:"query",request:{tenantId:"other-tenant",reportId:"status-performance",limit:10}}});assert.equal(other.data.payload.rows.length,0)});
