import test from "node:test";
import assert from "node:assert/strict";
import { requirementBindings } from "../dist/packages/requirements/registry.js";
import { AuthoritativeRecordService, AuthorizationService, BusinessValidationService, AuditEvidenceService, ExceptionHandlingService, GovernedReportingService } from "../dist/packages/capabilities/services.js";
const req=id=>{const r=requirementBindings.find(x=>x.id===id);assert.ok(r,"Missing governed requirement: "+id);return r};
const ctx=id=>({tenantId:"wave-11-ch473",principalId:"wave-11-runner",correlationId:id});

test("REQ-47301 / SRS-FR-2383: authoritative lifecycle",async()=>{const r=req("REQ-47301");assert.equal(r.pattern,"XX01");const s=new AuthoritativeRecordService();await s.execute(r,{context:ctx("47301-create"),payload:{operation:"create",record:{id:"47301-record",tenantId:"wave-11-ch473",version:1,state:"OPEN",data:{source:"wave-11"}}}});const u=await s.execute(r,{context:ctx("47301-update"),payload:{operation:"update",tenantId:"wave-11-ch473",id:"47301-record",expectedVersion:1,patch:{state:"CLOSED"}}});assert.equal(u.data.payload.record.version,2);assert.equal(u.data.payload.record.state,"CLOSED");assert.throws(()=>s.execute(r,{context:ctx("47301-stale"),payload:{operation:"update",tenantId:"wave-11-ch473",id:"47301-record",expectedVersion:1,patch:{state:"REOPENED"}}}),/RECORD_VERSION_CONFLICT/)});
test("REQ-47302 / SRS-FR-2384: authorization",async()=>{const r=req("REQ-47302");assert.equal(r.pattern,"XX02");const s=new AuthorizationService();const d=await s.execute(r,{context:ctx("47302-deny"),payload:{operation:"decide",request:{tenantId:"wave-11-ch473",principalId:"actor-47302",action:"material.update",resource:"authoritative-record"},policies:[{tenantId:"wave-11-ch473",principalId:"actor-47302",actions:["material.update"],resources:["authoritative-record"],effect:"ALLOW"},{tenantId:"wave-11-ch473",principalId:"actor-47302",actions:["material.update"],resources:["authoritative-record"],effect:"DENY"}]}});assert.equal(d.data.payload.decision.effect,"DENY");const dd=await s.execute(r,{context:ctx("47302-default"),payload:{operation:"decide",request:{tenantId:"wave-11-ch473",principalId:"unlisted",action:"material.delete",resource:"authoritative-record"}}});assert.equal(dd.data.payload.decision.effect,"DENY")});
test("REQ-47303 / SRS-FR-2385: business validation",async()=>{const r=req("REQ-47303");assert.equal(r.pattern,"XX03");const s=new BusinessValidationService();s.addRule({id:"47303-positive-amount",evaluate:i=>i?.amount>0?null:{code:"MANDATORY_CONDITION_FAILED",message:"Amount must be positive",severity:"ERROR"}});const v=await s.execute(r,{context:ctx("47303-valid"),payload:{operation:"validate",input:{amount:100}}});assert.equal(v.data.payload.validation.valid,true);const i=await s.execute(r,{context:ctx("47303-invalid"),payload:{operation:"validate",input:{amount:0}}});assert.equal(i.data.payload.validation.valid,false)});
test("REQ-47304 / SRS-FR-2386: audit integrity",async()=>{const r=req("REQ-47304");assert.equal(r.pattern,"XX04");const s=new AuditEvidenceService();const a=await s.execute(r,{context:ctx("47304-append"),payload:{operation:"append",evidence:{id:"47304-evidence",tenantId:"wave-11-ch473",requirementId:"REQ-47304",action:"MATERIAL_EVENT",principalId:"wave-11-runner",correlationId:"47304-append",occurredAt:"2026-09-25T03:00:00.000Z",payload:{result:"PASS"}}}});assert.match(a.data.payload.evidence.integrityHash,/^[a-f0-9]{64}$/);const own=await s.execute(r,{context:ctx("47304-list"),payload:{operation:"listByRequirement",tenantId:"wave-11-ch473",requirementId:"REQ-47304"}});assert.equal(own.data.payload.evidence.length,1)});
test("REQ-47305 / SRS-FR-2387: exception lifecycle",async()=>{const r=req("REQ-47305");assert.equal(r.pattern,"XX05");const s=new ExceptionHandlingService();await s.execute(r,{context:ctx("47305-create"),payload:{operation:"create",exception:{id:"47305-exception",tenantId:"wave-11-ch473",requirementId:"REQ-47305",code:"CONTROLLED_FAILURE",message:"Acceptance scenario",idempotencyKey:"47305-idempotency",createdAt:"2026-09-25T03:00:00.000Z"}}});const retry=await s.execute(r,{context:ctx("47305-retry"),payload:{operation:"transition",tenantId:"wave-11-ch473",id:"47305-exception",patch:{state:"RETRYING"}}});assert.equal(retry.data.payload.exception.state,"RETRYING");const resolved=await s.execute(r,{context:ctx("47305-resolve"),payload:{operation:"transition",tenantId:"wave-11-ch473",id:"47305-exception",patch:{state:"RESOLVED"}}});assert.equal(resolved.data.payload.exception.state,"RESOLVED");assert.throws(()=>s.execute(r,{context:ctx("47305-invalid"),payload:{operation:"transition",tenantId:"wave-11-ch473",id:"47305-exception",patch:{state:"RETRYING"}}}),/EXCEPTION_INVALID_TRANSITION/)});
test("REQ-47306 / SRS-FR-2388: governed reporting",async()=>{const r=req("REQ-47306");assert.equal(r.pattern,"XX06");const s=new GovernedReportingService();await s.execute(r,{context:ctx("47306-publish"),payload:{operation:"publish",row:{tenantId:"wave-11-ch473",reportId:"status-performance",values:{state:"OPEN",performance:99},sourceRequirementIds:["REQ-47306"],generatedAt:"2026-09-25T03:00:00.000Z"}}});const own=await s.execute(r,{context:ctx("47306-query"),payload:{operation:"query",request:{tenantId:"wave-11-ch473",reportId:"status-performance",filters:{state:"OPEN"},limit:10}}});assert.equal(own.data.payload.rows.length,1);const other=await s.execute(r,{context:{...ctx("47306-other"),tenantId:"other-tenant"},payload:{operation:"query",request:{tenantId:"other-tenant",reportId:"status-performance",limit:10}}});assert.equal(other.data.payload.rows.length,0)});